# This file was generated by GoReleaser. DO NOT EDIT.
cask "tweak" do
  name "tweak"
  desc "Fast CLI + TUI for text processing: encoding, hashing, transforms, and more."
  homepage "https://github.com/OpenSyntaxHQ/tweak"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tweak"

  on_macos do
    url "https://github.com/OpenSyntaxHQ/tweak/releases/download/v#{version}/tweak_Darwin_all.tar.gz"
    sha256 "c326b941defc374ae7570bf143e21679650405866c82157727e5c775d941ad3e"
  end

  on_linux do
    on_intel do
      url "https://github.com/OpenSyntaxHQ/tweak/releases/download/v#{version}/tweak_Linux_x86_64.tar.gz"
      sha256 "4c3b3bbbe13b6c45ed15e4d5ac6f500b47a3cc95eb2c30f31f389d94c38b49eb"
    end
    on_arm do
      url "https://github.com/OpenSyntaxHQ/tweak/releases/download/v#{version}/tweak_Linux_arm64.tar.gz"
      sha256 "fc07a9fe7f910b7003b8b644bc55ddecf248d959c8ecc2268681bb43c52a2ddf"
    end
  end

  # No zap stanza required
end
